#!/bin/bash

export DOCKER_CLI_EXPERIMENTAL=enabled

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --name local
docker buildx use local
docker buildx inspect --bootstrap
